services:  
  - type: web  
    name: bluewave-oil-gas-website  
    env: python  
    buildCommand: ""  
    startCommand: gunicorn app:app  
    envVars:  
      - key: FLASK_ENV  
        value: production 
